title: Tazkera Haque # your name (or website title) here
logo: "images/dummy_thumbnail.jpg # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
M.Sc. in Physics | Team Lead Coding Instructor and Mentor | Passionate about Data Science
<br><br>
  <a href="www.linkedin.com/in/tazkera-haque>View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
